### ISSUE TITLE
Errors in page navigation

### ISSUE THREAD

**Issue by maneesha** [sfbrigade/Mobile-Fusion-Tables#51]
Not sure if anyone's maintaining this project anymore.  I may do some digging around to see if I can find out what's going on but I'm submitting this issue in case someone already knows what's going on.

For any site using MFT template (including the demos and other apps listed on repo's readme):

Initial page loads fine.  But if you then click to one of the other pages like About or Search and then use the app's `Back` button (not the browser's back button) the map flashes on the screen and then it goes blank.

If you click on `List` then click the app's `Back` button, it seems to take you back to the map just fine.  But then if you click on `Search`, the `List` page gets overlaid on the `Search` page.

I use the template for www.toynbeeidea.com but you'll see the same problem on any of the apps using this template.

**Comment by maneesha** [comment]
UPDATE : I've discovered this is due to outdated jquery libraries.  I'll be submitting a PR in the next few days.

**Comment by Taul123** [comment]
Hi maneesha,
If you have a potential solution to this issue, then I would be very grateful. 
I'm using the template for the uk fabricators.

**Comment by maneesha** [comment]
Sure. I'll be submitting a PR sometime this week.  I don't know if the owners of this repo are still watching this, but even if they don't merge it you'll be able to see it so you can see and make the changes yourself.

**Comment by regosen** [comment]
Hi folks,

Apologies for not maintaining this repository.  I think most people have moved on... but I hate to leave things in such a broken state, so I've investigated and fixed these navigation issues just now.

If you want to fix your own versions you'll want to:
(a) replace maps_lib.js with the latest version.
(b) replace the <body> block of your index with the latest version.

I hope this helps someone  :)
