### ISSUE TITLE
Marker Animation block pages

### ISSUE THREAD

**Issue by themonki** [sfbrigade/Mobile-Fusion-Tables#53]
When searching for a place or allowing the location to be obtained, the bookmark animation is blocking.

1. Go to http://www.mobilefusiontables.com/demo-USHealthCenters.html
2. Go to Search and enter any location.
3. For a moment you see the animation of the bookmark but it immediately returns you to the search page, but the page is blocked.

This also applies when you have the nearby marker, if you go to the about page, it happens the same when you click on Back

I found a solution and it was to remove the lines on 'map_lib.js':

```js
                         animation: google.maps.Animation.DROP
```

![image](https://user-images.githubusercontent.com/1817333/38522224-84746208-3c0d-11e8-82c0-4d38736e6d05.png)

**Comment by regosen** [comment]
Thank you for finding the fix!  I've just submitted the update.
