### ISSUE TITLE
ERROR: please check your settings file! Bad Request

### ISSUE THREAD

**Issue by odomojuli** [sfbrigade/Mobile-Fusion-Tables#54]
`ERROR: please check your settings file! Bad Request`

I get the following error upon inputting the appropriate API Key and ID for my Fusion Table.
Setup is relatively straightforward so I'm not sure what the issue is here.

**Comment by regosen** [comment]
Can you send me the fusion table ID you used?  API key would help too, but I understand if you'd rather not share that here.  (You can find my email address in my profile.)
